import { Person} from "./Person";
import { JuridicalPerson} from "./JuridicalPerson";
import { Employee} from "./Employee";
import { Counter} from "./Counter";
import { Balance} from "./Balance";
import { Appointment} from "./Appointment";
import { UserPayment} from "./UserPayment";
import { TaxReceipt} from "./TaxReceipt";
import { TaxSettings} from "./TaxSettings";
import { UserAttachment} from "./UserAttachment";
import { Approval} from "./Approval";
import { ScreenPermission} from "./ScreenPermission";
import { PrepayTax} from "./PrepayTax";
import { WithdrawMoney} from "./WithdrawMoney";
import { MainBankAccount} from "./MainBankAccount";
import { HelpCenterMessages} from "./HelpCenterMessages";
import { HelpCenter} from "./HelpCenter";
import { HelpCenterService} from "./HelpCenterService";
import { UserLogin} from "./UserLogin";
import { UserTwoStepsVerification} from "./UserTwoStepsVerification";
import { LogBackuped} from "./LogBackuped";
import { ServiceOrderCanceled} from "./ServiceOrderCanceled";
import { ServiceOrderAttachment} from "./ServiceOrderAttachment";
import { FinancialModule} from "./FinancialModule";

export class User {
  pkUser: number;
  username: string;
  password: string;
  dateOfCreatingAccount: Date = new Date();
  dateOfFinishingAccount: Date = new Date();
  facebookAccount: String;
  useTwoStepsVerification: boolean;
  status: number = 0;
  person: Person = new Person();
  juridicalPerson: JuridicalPerson = new JuridicalPerson();
  employee: Employee = new Employee();
  counter: Counter = new Counter();
  balance: Balance = new Balance();
  userAppointmentList: Array<Appointment> = new Array<Appointment>();
  userUserPaymentList: Array<UserPayment> = new Array<UserPayment>();
  userTaxReceiptList: Array<TaxReceipt> = new Array<TaxReceipt>();
  userTaxSettingsList: Array<TaxSettings> = new Array<TaxSettings>();
  userUserAttachmentList: Array<UserAttachment> = new Array<UserAttachment>();
  userApprovalList: Array<Approval> = new Array<Approval>();
  userScreenPermissionList: Array<ScreenPermission> = new Array<ScreenPermission>();
  userPrepayTaxList: Array<PrepayTax> = new Array<PrepayTax>();
  userWithdrawMoneyList: Array<WithdrawMoney> = new Array<WithdrawMoney>();
  userCreatorMainBankAccountList: Array<MainBankAccount> = new Array<MainBankAccount>();
  userHelpCenterMessagesList: Array<HelpCenterMessages> = new Array<HelpCenterMessages>();
  userCompanyHelpCenterMessagesList: Array<HelpCenterMessages> = new Array<HelpCenterMessages>();
  userHelpCenterList: Array<HelpCenter> = new Array<HelpCenter>();
  userHelpCenterServiceList: Array<HelpCenterService> = new Array<HelpCenterService>();
  userUserLoginList: Array<UserLogin> = new Array<UserLogin>();
  userUserTwoStepsVerificationList: Array<UserTwoStepsVerification> = new Array<UserTwoStepsVerification>();
  userLogBackupedList: Array<LogBackuped> = new Array<LogBackuped>();
  userServiceOrderCanceledList: Array<ServiceOrderCanceled> = new Array<ServiceOrderCanceled>();
  userServiceOrderAttachmentList: Array<ServiceOrderAttachment> = new Array<ServiceOrderAttachment>();
  userFinancialModuleList: Array<FinancialModule> = new Array<FinancialModule>();
}